### ISSUE TITLE
suggestion for code enhancement

### ISSUE THREAD

**Issue by goruck** [gabrielsaintangel/SNPedia_23andme_processing#1]
Here's a suggested enhancement to make the code more readable and Pythonic.

Change this [function](https://github.com/gabrielsaintangel/SNPedia_23andme_processing/blob/cf8fcbf7da9e3cac934317d77effd9f509297552/main.py#L43) to something like this:

```python
def get_common_snps(your_data, documented_snps) -> list:
    return [snp for snp in documented_snps if snp in your_data]
```

**Comment by gabrielsaintangel** [comment]
Fixed, thanks.
